export const countryMapper = {
  AD: 'and',
  AE: 'are',
  AF: 'afg',
  AG: 'atg',
  AI: 'aia',
  AL: 'alb',
  AM: 'arm',
  AO: 'ago',
  AR: 'arg',
  AS: 'asm',
  AT: 'aut',
  AU: 'aus',
  AW: 'abw',
  AX: 'ala',
  AZ: 'aze',
  BA: 'bih',
  BB: 'brb',
  BD: 'bgd',
  BE: 'bel',
  BF: 'bfa',
  BG: 'bgr',
  BH: 'bhr',
  BI: 'bdi',
  BJ: 'ben',
  BL: 'blm',
  BM: 'bmu',
  BN: 'brn',
  BO: 'bol',
  BQ: 'bq',
  BR: 'bra',
  BS: 'bhs',
  BT: 'btn',
  BW: 'bwa',
  BY: 'blr',
  BZ: 'blz',
  CA: 'can',
  CC: 'cck',
  CD: 'cod',
  CF: 'caf',
  CG: 'cog',
  CH: 'che',
  CI: 'civ',
  CK: 'cok',
  CL: 'chl',
  CM: 'cmr',
  CN: 'chn',
  CO: 'col',
  CR: 'cri',
  CU: 'cub',
  CV: 'cpv',
  CW: 'cuw',
  CY: 'cyp',
  CZ: 'cze',
  DE: 'deu',
  DJ: 'dji',
  DK: 'dnk',
  DM: 'dma',
  DO: 'dom',
  DZ: 'dza',
  EC: 'ecu',
  EE: 'est',
  EG: 'egy',
  EH: 'esh',
  ER: 'eri',
  ES: 'esp',
  ET: 'eth',
  FI: 'fin',
  FJ: 'fji',
  FK: 'flk',
  FM: 'fsm',
  FO: 'fro',
  FR: 'fra',
  GA: 'gab',
  GB: 'gbr',
  GD: 'grd',
  GE: 'geo',
  GF: 'guf',
  GG: 'ggy',
  GH: 'gha',
  GI: 'gib',
  GL: 'grl',
  GM: 'gmb',
  GN: 'gin',
  GQ: 'gnq',
  GR: 'grc',
  GT: 'gtm',
  GU: 'gum',
  GW: 'gnb',
  GY: 'guy',
  HK: 'hkg',
  HN: 'hnd',
  HR: 'hrv',
  HT: 'hti',
  HU: 'hun',
  ID: 'idn',
  IE: 'irl',
  IL: 'isr',
  IM: 'imn',
  IN: 'ind',
  IO: 'iot',
  IQ: 'irq',
  IR: 'irn',
  IS: 'isl',
  IT: 'ita',
  JE: 'jey',
  JM: 'jam',
  JO: 'jor',
  JP: 'jpn',
  KE: 'ken',
  KG: 'kgz',
  KH: 'khm',
  KI: 'kir',
  KM: 'com',
  KN: 'kna',
  KP: 'prk',
  KR: 'kor',
  KW: 'kwt',
  KY: 'cym',
  KZ: 'kaz',
  LA: 'lao',
  LB: 'lbn',
  LC: 'lca',
  LI: 'lie',
  LK: 'lka',
  LR: 'lbr',
  LS: 'lso',
  LT: 'ltu',
  LU: 'lux',
  LV: 'lva',
  LY: 'lby',
  MA: 'mar',
  MC: 'mco',
  MD: 'mda',
  ME: 'mne',
  MG: 'mdg',
  MH: 'mhl',
  MK: 'mkd',
  ML: 'mli',
  MM: 'mmr',
  MN: 'mng',
  MO: 'mac',
  MP: 'mnp',
  MQ: 'mtq',
  MR: 'mrt',
  MS: 'msr',
  MT: 'mlt',
  MU: 'mus',
  MV: 'mdv',
  MW: 'mwi',
  MX: 'mex',
  MY: 'mys',
  MZ: 'moz',
  NA: 'nam',
  NC: 'ncl',
  NE: 'ner',
  NF: 'nfk',
  NG: 'nga',
  NI: 'nic',
  NL: 'nld',
  NO: 'nor',
  NP: 'npl',
  NR: 'nru',
  NU: 'niu',
  NZ: 'nzl',
  OM: 'omn',
  PA: 'pan',
  PE: 'per',
  PF: 'pyf',
  PG: 'png',
  PH: 'phl',
  PK: 'pak',
  PL: 'pol',
  PR: 'pri',
  PS: 'pse',
  PT: 'prt',
  PW: 'plw',
  PY: 'pry',
  QA: 'qat',
  RO: 'rou',
  RS: 'srb',
  RU: 'rus',
  RW: 'rwa',
  SA: 'sau',
  SB: 'slb',
  SC: 'syc',
  SD: 'sdn',
  SE: 'swe',
  SG: 'sgp',
  SI: 'svn',
  SJ: 'sjm',
  SK: 'svk',
  SL: 'sle',
  SM: 'smr',
  SN: 'sen',
  SO: 'som',
  SR: 'sur',
  SS: 'ssd',
  ST: 'stp',
  SV: 'slv',
  SX: 'sxm',
  SY: 'syr',
  SZ: 'swz',
  TA: 'tkl',
  TC: 'tca',
  TD: 'tcd',
  TG: 'tgo',
  TH: 'tha',
  TJ: 'tjk',
  TK: 'tkm',
  TL: 'tls',
  TM: 'tuv',
  TN: 'tun',
  TO: 'ton',
  TR: 'tur',
  TT: 'tto',
  TV: 'tuv',
  TW: 'twn',
  TZ: 'tza',
  UA: 'ukr',
  UG: 'uga',
  US: 'usa',
  UY: 'ury',
  UZ: 'uzb',
  VA: 'vat',
  VC: 'vct',
  VE: 'ven',
  VG: 'vgb',
  VI: 'vir',
  VN: 'vnm',
  VU: 'vut',
  WF: 'wlf',
  WS: 'wsm',
  XK: 'xkx',
  YE: 'yem',
  ZA: 'zaf',
  ZM: 'zmb',
  ZW: 'zwe',
}

// Country code to country name mapping
export const countryList = [
  { code: 'AF', name: 'Afghanistan' },
  { code: 'AL', name: 'Albania' },
  { code: 'DZ', name: 'Algeria' },
  { code: 'AS', name: 'American Samoa' },
  { code: 'AD', name: 'Andorra' },
  { code: 'AO', name: 'Angola' },
  { code: 'AI', name: 'Anguilla' },
  { code: 'AQ', name: 'Antarctica' },
  { code: 'AG', name: 'Antigua and Barbuda' },
  { code: 'AR', name: 'Argentina' },
  { code: 'AM', name: 'Armenia' },
  { code: 'AW', name: 'Aruba' },
  { code: 'AU', name: 'Australia' },
  { code: 'AT', name: 'Austria' },
  { code: 'AZ', name: 'Azerbaijan' },
  { code: 'BS', name: 'Bahamas' },
  { code: 'BH', name: 'Bahrain' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'BB', name: 'Barbados' },
  { code: 'BY', name: 'Belarus' },
  { code: 'BE', name: 'Belgium' },
  { code: 'BZ', name: 'Belize' },
  { code: 'BJ', name: 'Benin' },
  { code: 'BM', name: 'Bermuda' },
  { code: 'BT', name: 'Bhutan' },
  { code: 'BO', name: 'Bolivia' },
  { code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba' },
  { code: 'BA', name: 'Bosnia and Herzegovina' },
  { code: 'BW', name: 'Botswana' },
  { code: 'BV', name: 'Bouvet Island' },
  { code: 'BR', name: 'Brazil' },
  { code: 'IO', name: 'British Indian Ocean Territory' },
  { code: 'BN', name: 'Brunei Darussalam' },
  { code: 'BG', name: 'Bulgaria' },
  { code: 'BF', name: 'Burkina Faso' },
  { code: 'BI', name: 'Burundi' },
  { code: 'KH', name: 'Cambodia' },
  { code: 'CM', name: 'Cameroon' },
  { code: 'CA', name: 'Canada' },
  { code: 'CV', name: 'Cabo Verde' },
  { code: 'KY', name: 'Cayman Islands' },
  { code: 'CF', name: 'Central African Republic' },
  { code: 'TD', name: 'Chad' },
  { code: 'CL', name: 'Chile' },
  { code: 'CN', name: 'China' },
  { code: 'CX', name: 'Christmas Island' },
  { code: 'CC', name: 'Cocos (Keeling) Islands' },
  { code: 'CO', name: 'Colombia' },
  { code: 'KM', name: 'Comoros' },
  { code: 'CG', name: 'Congo' },
  { code: 'CD', name: 'Congo, Democratic Republic of the' },
  { code: 'CK', name: 'Cook Islands' },
  { code: 'CR', name: 'Costa Rica' },
  { code: 'CI', name: "Côte d'Ivoire" },
  { code: 'HR', name: 'Croatia' },
  { code: 'CU', name: 'Cuba' },
  { code: 'CW', name: 'Curaçao' },
  { code: 'CY', name: 'Cyprus' },
  { code: 'CZ', name: 'Czechia' },
  { code: 'DK', name: 'Denmark' },
  { code: 'DJ', name: 'Djibouti' },
  { code: 'DM', name: 'Dominica' },
  { code: 'DO', name: 'Dominican Republic' },
  { code: 'EC', name: 'Ecuador' },
  { code: 'EG', name: 'Egypt' },
  { code: 'SV', name: 'El Salvador' },
  { code: 'GQ', name: 'Equatorial Guinea' },
  { code: 'ER', name: 'Eritrea' },
  { code: 'EE', name: 'Estonia' },
  { code: 'SZ', name: 'Eswatini' },
  { code: 'ET', name: 'Ethiopia' },
  { code: 'FK', name: 'Falkland Islands' },
  { code: 'FO', name: 'Faroe Islands' },
  { code: 'FJ', name: 'Fiji' },
  { code: 'FI', name: 'Finland' },
  { code: 'FR', name: 'France' },
  { code: 'GF', name: 'French Guiana' },
  { code: 'PF', name: 'French Polynesia' },
  { code: 'TF', name: 'French Southern Territories' },
  { code: 'GA', name: 'Gabon' },
  { code: 'GM', name: 'Gambia' },
  { code: 'GE', name: 'Georgia' },
  { code: 'DE', name: 'Germany' },
  { code: 'GH', name: 'Ghana' },
  { code: 'GI', name: 'Gibraltar' },
  { code: 'GR', name: 'Greece' },
  { code: 'GL', name: 'Greenland' },
  { code: 'GD', name: 'Grenada' },
  { code: 'GP', name: 'Guadeloupe' },
  { code: 'GU', name: 'Guam' },
  { code: 'GT', name: 'Guatemala' },
  { code: 'GG', name: 'Guernsey' },
  { code: 'GN', name: 'Guinea' },
  { code: 'GW', name: 'Guinea-Bissau' },
  { code: 'GY', name: 'Guyana' },
  { code: 'HT', name: 'Haiti' },
  { code: 'HM', name: 'Heard Island and McDonald Islands' },
  { code: 'VA', name: 'Vatican City' },
  { code: 'HN', name: 'Honduras' },
  { code: 'HK', name: 'Hong Kong' },
  { code: 'HU', name: 'Hungary' },
  { code: 'IS', name: 'Iceland' },
  { code: 'IN', name: 'India' },
  { code: 'ID', name: 'Indonesia' },
  { code: 'IR', name: 'Iran' },
  { code: 'IQ', name: 'Iraq' },
  { code: 'IE', name: 'Ireland' },
  { code: 'IM', name: 'Isle of Man' },
  { code: 'IL', name: 'Israel' },
  { code: 'IT', name: 'Italy' },
  { code: 'JM', name: 'Jamaica' },
  { code: 'JP', name: 'Japan' },
  { code: 'JE', name: 'Jersey' },
  { code: 'JO', name: 'Jordan' },
  { code: 'KZ', name: 'Kazakhstan' },
  { code: 'KE', name: 'Kenya' },
  { code: 'KI', name: 'Kiribati' },
  { code: 'KP', name: "Korea (Democratic People's Republic of)" },
  { code: 'KR', name: 'Korea (Republic of)' },
  { code: 'KW', name: 'Kuwait' },
  { code: 'KG', name: 'Kyrgyzstan' },
  { code: 'LA', name: "Lao People's Democratic Republic" },
  { code: 'LV', name: 'Latvia' },
  { code: 'LB', name: 'Lebanon' },
  { code: 'LS', name: 'Lesotho' },
  { code: 'LR', name: 'Liberia' },
  { code: 'LY', name: 'Libya' },
  { code: 'LI', name: 'Liechtenstein' },
  { code: 'LT', name: 'Lithuania' },
  { code: 'LU', name: 'Luxembourg' },
  { code: 'MO', name: 'Macao' },
  { code: 'MG', name: 'Madagascar' },
  { code: 'MW', name: 'Malawi' },
  { code: 'MY', name: 'Malaysia' },
  { code: 'MV', name: 'Maldives' },
  { code: 'ML', name: 'Mali' },
  { code: 'MT', name: 'Malta' },
  { code: 'MH', name: 'Marshall Islands' },
  { code: 'MQ', name: 'Martinique' },
  { code: 'MR', name: 'Mauritania' },
  { code: 'MU', name: 'Mauritius' },
  { code: 'YT', name: 'Mayotte' },
  { code: 'MX', name: 'Mexico' },
  { code: 'FM', name: 'Micronesia' },
  { code: 'MD', name: 'Moldova' },
  { code: 'MC', name: 'Monaco' },
  { code: 'MN', name: 'Mongolia' },
  { code: 'ME', name: 'Montenegro' },
  { code: 'MS', name: 'Montserrat' },
  { code: 'MA', name: 'Morocco' },
  { code: 'MZ', name: 'Mozambique' },
  { code: 'MM', name: 'Myanmar' },
  { code: 'NA', name: 'Namibia' },
  { code: 'NR', name: 'Nauru' },
  { code: 'NP', name: 'Nepal' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'NC', name: 'New Caledonia' },
  { code: 'NZ', name: 'New Zealand' },
  { code: 'NI', name: 'Nicaragua' },
  { code: 'NE', name: 'Niger' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'NU', name: 'Niue' },
  { code: 'NF', name: 'Norfolk Island' },
  { code: 'MP', name: 'Northern Mariana Islands' },
  { code: 'NO', name: 'Norway' },
  { code: 'OM', name: 'Oman' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'PW', name: 'Palau' },
  { code: 'PS', name: 'Palestine, State of' },
  { code: 'PA', name: 'Panama' },
  { code: 'PG', name: 'Papua New Guinea' },
  { code: 'PY', name: 'Paraguay' },
  { code: 'PE', name: 'Peru' },
  { code: 'PH', name: 'Philippines' },
  { code: 'PN', name: 'Pitcairn' },
  { code: 'PL', name: 'Poland' },
  { code: 'PT', name: 'Portugal' },
  { code: 'PR', name: 'Puerto Rico' },
  { code: 'QA', name: 'Qatar' },
  { code: 'RE', name: 'Réunion' },
  { code: 'RO', name: 'Romania' },
  { code: 'RU', name: 'Russian Federation' },
  { code: 'RW', name: 'Rwanda' },
  { code: 'BL', name: 'Saint Barthélemy' },
  { code: 'SH', name: 'Saint Helena, Ascension and Tristan da Cunha' },
  { code: 'KN', name: 'Saint Kitts and Nevis' },
  { code: 'LC', name: 'Saint Lucia' },
  { code: 'MF', name: 'Saint Martin (French part)' },
  { code: 'PM', name: 'Saint Pierre and Miquelon' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines' },
  { code: 'WS', name: 'Samoa' },
  { code: 'SM', name: 'San Marino' },
  { code: 'ST', name: 'Sao Tome and Principe' },
  { code: 'SA', name: 'Saudi Arabia' },
  { code: 'SN', name: 'Senegal' },
  { code: 'RS', name: 'Serbia' },
  { code: 'SC', name: 'Seychelles' },
  { code: 'SL', name: 'Sierra Leone' },
  { code: 'SG', name: 'Singapore' },
  { code: 'SX', name: 'Sint Maarten' },
  { code: 'SK', name: 'Slovakia' },
  { code: 'SI', name: 'Slovenia' },
  { code: 'SB', name: 'Solomon Islands' },
  { code: 'SO', name: 'Somalia' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'GS', name: 'South Georgia and the South Sandwich Islands' },
  { code: 'SS', name: 'South Sudan' },
  { code: 'ES', name: 'Spain' },
  { code: 'LK', name: 'Sri Lanka' },
  { code: 'SD', name: 'Sudan' },
  { code: 'SR', name: 'Suriname' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen' },
  { code: 'SE', name: 'Sweden' },
  { code: 'CH', name: 'Switzerland' },
  { code: 'SY', name: 'Syrian Arab Republic' },
  { code: 'TW', name: 'Taiwan' },
  { code: 'TJ', name: 'Tajikistan' },
  { code: 'TZ', name: 'Tanzania' },
  { code: 'TH', name: 'Thailand' },
  { code: 'TL', name: 'Timor-Leste' },
  { code: 'TG', name: 'Togo' },
  { code: 'TK', name: 'Tokelau' },
  { code: 'TO', name: 'Tonga' },
  { code: 'TT', name: 'Trinidad and Tobago' },
  { code: 'TN', name: 'Tunisia' },
  { code: 'TR', name: 'Turkey' },
  { code: 'TM', name: 'Turkmenistan' },
  { code: 'TC', name: 'Turks and Caicos Islands' },
  { code: 'TV', name: 'Tuvalu' },
  { code: 'UG', name: 'Uganda' },
  { code: 'UA', name: 'Ukraine' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'US', name: 'United States' },
  { code: 'UM', name: 'United States Minor Outlying Islands' },
  { code: 'UY', name: 'Uruguay' },
  { code: 'UZ', name: 'Uzbekistan' },
  { code: 'VU', name: 'Vanuatu' },
  { code: 'VE', name: 'Venezuela' },
  { code: 'VN', name: 'Viet Nam' },
  { code: 'VG', name: 'Virgin Islands (British)' },
  { code: 'VI', name: 'Virgin Islands (U.S.)' },
  { code: 'WF', name: 'Wallis and Futuna' },
  { code: 'EH', name: 'Western Sahara' },
  { code: 'YE', name: 'Yemen' },
  { code: 'ZM', name: 'Zambia' },
  { code: 'ZW', name: 'Zimbabwe' },
]

/**
 * List of country codes to ignore in UI or logic.
 * Example usage: import { ignoredCountries } from '@/constants/countries'
 * and filter countryList/countryMapper as needed.
 */
export const ignoredCountries: string[] = [
  'AC',
  'GP',
  'MF',
  'CX',
  'KN',
  'WF',
  'YT',
  'RE',
  'SH',
  'PM',
  'IO',
  'CC',
  'GF',
  'NC',
  'PS',
  'SJ',
  'EH',
]
