<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit0b1b43ebdc1a9131852decb4328c5e01
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('IvyForms\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \IvyForms\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit0b1b43ebdc1a9131852decb4328c5e01', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \IvyForms\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit0b1b43ebdc1a9131852decb4328c5e01', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\IvyForms\Vendor\Composer\Autoload\ComposerStaticInit0b1b43ebdc1a9131852decb4328c5e01::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        $filesToLoad = \IvyForms\Vendor\Composer\Autoload\ComposerStaticInit0b1b43ebdc1a9131852decb4328c5e01::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }

        return $loader;
    }
}
